// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
)

// Migrations is the golang structure for table migrations.
type Migrations struct {
	IdMigration        uint        `orm:"id_migration,primary" json:"idMigration"`        // surrogate key
	Name               string      `orm:"name"                 json:"name"`               // migration name, unique
	CreatedAt          *gtime.Time `orm:"created_at"           json:"createdAt"`          // date migrated or rolled back
	Statements         string      `orm:"statements"           json:"statements"`         // SQL statements for this migration
	RollbackStatements string      `orm:"rollback_statements"  json:"rollbackStatements"` // SQL statment for rolling back migration
	Status             string      `orm:"status"               json:"status"`             // update indicates it is a normal migration while rollback means this migration is rolled back
}

// Users is the golang structure for table users.
type Users struct {
	Id              uint        `orm:"id,primary"        json:"id"`              //
	Name            string      `orm:"name"              json:"name"`            //
	Email           string      `orm:"email"             json:"email"`           //
	Password        string      `orm:"password"          json:"password"`        //
	RememberToken   string      `orm:"remember_token"    json:"rememberToken"`   //
	EmailVerifiedAt string      `orm:"email_verified_at" json:"emailVerifiedAt"` //
	CreatedAt       *gtime.Time `orm:"created_at"        json:"createdAt"`       //
	UpdatedAt       *gtime.Time `orm:"updated_at"        json:"updatedAt"`       //
	Avatar          string      `orm:"avatar"            json:"avatar"`          //
	Introduction    string      `orm:"introduction"      json:"introduction"`    //
}
