// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GoFrame-weibo/app/dao/internal"
)

// imagesDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type imagesDao struct {
	*internal.ImagesDao
}

var (
	// Images is globally public accessible object for table images operations.
	Images = imagesDao{
		internal.NewImagesDao(),
	}
)

// Fill with you ideas below.
