// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GoFrame-weibo/app/dao/internal"
)

// linksDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type linksDao struct {
	*internal.LinksDao
}

var (
	// Links is globally public accessible object for table links operations.
	Links = linksDao{
		internal.NewLinksDao(),
	}
)

// Fill with you ideas below.
