// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GoFrame-weibo/app/dao/internal"
)

// modelHasPermissionsDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type modelHasPermissionsDao struct {
	*internal.ModelHasPermissionsDao
}

var (
	// ModelHasPermissions is globally public accessible object for table model_has_permissions operations.
	ModelHasPermissions = modelHasPermissionsDao{
		internal.NewModelHasPermissionsDao(),
	}
)

// Fill with you ideas below.
