// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GoFrame-weibo/app/dao/internal"
)

// notificationsDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type notificationsDao struct {
	*internal.NotificationsDao
}

var (
	// Notifications is globally public accessible object for table notifications operations.
	Notifications = notificationsDao{
		internal.NewNotificationsDao(),
	}
)

// Fill with you ideas below.
