// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GoFrame-weibo/app/dao/internal"
)

// repliesDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type repliesDao struct {
	*internal.RepliesDao
}

var (
	// Replies is globally public accessible object for table replies operations.
	Replies = repliesDao{
		internal.NewRepliesDao(),
	}
)

// Fill with you ideas below.
