// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GoFrame-weibo/app/dao/internal"
)

// rolesDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type rolesDao struct {
	*internal.RolesDao
}

var (
	// Roles is globally public accessible object for table roles operations.
	Roles = rolesDao{
		internal.NewRolesDao(),
	}
)

// Fill with you ideas below.
