// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// FailedJobsDao is the manager for logic model data accessing and custom defined data operations functions management.
type FailedJobsDao struct {
	Table   string            // Table is the underlying table name of the DAO.
	Group   string            // Group is the database configuration group name of current DAO.
	Columns FailedJobsColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// FailedJobsColumns defines and stores column names for table failed_jobs.
type FailedJobsColumns struct {
	Id         string //
	Connection string //
	Queue      string //
	Payload    string //
	Exception  string //
	FailedAt   string //
}

//  failedJobsColumns holds the columns for table failed_jobs.
var failedJobsColumns = FailedJobsColumns{
	Id:         "id",
	Connection: "connection",
	Queue:      "queue",
	Payload:    "payload",
	Exception:  "exception",
	FailedAt:   "failed_at",
}

// NewFailedJobsDao creates and returns a new DAO object for table data access.
func NewFailedJobsDao() *FailedJobsDao {
	return &FailedJobsDao{
		Group:   "default",
		Table:   "failed_jobs",
		Columns: failedJobsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *FailedJobsDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *FailedJobsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *FailedJobsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
