// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// ImagesDao is the manager for logic model data accessing and custom defined data operations functions management.
type ImagesDao struct {
	Table   string        // Table is the underlying table name of the DAO.
	Group   string        // Group is the database configuration group name of current DAO.
	Columns ImagesColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// ImagesColumns defines and stores column names for table images.
type ImagesColumns struct {
	Id        string //
	UserId    string //
	Type      string //
	Path      string //
	CreatedAt string //
	UpdatedAt string //
}

//  imagesColumns holds the columns for table images.
var imagesColumns = ImagesColumns{
	Id:        "id",
	UserId:    "user_id",
	Type:      "type",
	Path:      "path",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewImagesDao creates and returns a new DAO object for table data access.
func NewImagesDao() *ImagesDao {
	return &ImagesDao{
		Group:   "default",
		Table:   "images",
		Columns: imagesColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ImagesDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ImagesDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ImagesDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
